import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Group } from '../src/engine/index.js';
import { parseGLB } from '../src/engine/loaders/GLTF.js';
import { GPU } from '../src/engine/gpu/GPU.js';
import { SkinnedModel } from '../src/engine/render/Skinning.js';
import { RemoteAvatar, avatarTriangles } from '../src/player/RemoteAvatar.js';
import { avatarMaterialOptions } from '../src/player/AvatarMaterials.js';
import { DEFAULT_APPEARANCE } from '../src/player/AvatarAppearance.js';

const male = parseGLB(readFileSync(new URL('../public/models/characters/stock-player.glb', import.meta.url)));
const female = parseGLB(readFileSync(new URL('../public/models/characters/stock-female.glb', import.meta.url)));
assert.equal(avatarTriangles(male), 7364); assert.equal(avatarTriangles(female), 8732);
for (const source of [male, female]) for (const clip of ['idle', 'walk', 'run', 'helm']) assert.ok(source.animations.some(a => a.name === clip));
const created = [];
function model(duration = 2) {
	const fade = { x: 1, y: 0, set(x, y) { this.x = x; this.y = y; } };
	const result = { group: new Group(), materials: [{ uniforms: { shirt: { value: null }, lodFade: { value: fade } } }], disposed: 0, layers: [], clipNames: () => ['idle', 'walk', 'run', 'helm'], clipDuration: () => duration, play(clip, { from = 0 } = {}) { this.current = clip; this.layers = [{ clip: { name: clip }, time: from, target: 1 }]; }, update(dt) { this.dt = dt; for (const layer of this.layers) layer.time += dt; }, dispose() { this.disposed++; } };
	created.push(result); return result;
}
let resolveMale;
const avatar = new RemoteAvatar({ loadSource: asset => asset === 'stock-player' ? new Promise(resolve => { resolveMale = resolve; }) : Promise.resolve(female), createModel: async () => model() });
await avatar.setAppearance({ ...DEFAULT_APPEARANCE, style: 'female' });
const current = avatar.model;
resolveMale(male); await Promise.resolve(); await Promise.resolve();
assert.equal(avatar.model, current, 'Obsolete asset load cannot replace latest style');
await avatar.setAppearance({ ...DEFAULT_APPEARANCE, style: 'female', shirt: '#123456' });
assert.equal(created.length, 1, 'Color changes reuse model');
assert.ok(current.materials[0].uniforms.shirt.value);
avatar.update(.1, { position: [2, 3, 4], yaw: .5, moving: true, mode: 'walk', appearance: avatar.appearance });
assert.deepEqual(avatar.group.position.toArray(), [2, 3, 4]); assert.equal(current.current, 'walk');
avatar.update(.1, { position: [3, 3, 4], yaw: .5, moving: true, mode: 'walk', appearance: avatar.appearance });
assert.equal(current.current, 'run');
const scene = new Group(); scene.add(avatar.group); avatar.dispose(); avatar.dispose();
assert.equal(current.disposed, 1); assert.equal(scene.children.length, 0);
let finishModel;
const pending = new RemoteAvatar({ loadSource: async () => male, createModel: () => new Promise(resolve => { finishModel = resolve; }) });
await Promise.resolve(); pending.dispose(); const late = model(); finishModel(late); await pending.ready;
assert.equal(late.disposed, 1, 'Model completed after departure releases resources');
const capped = new RemoteAvatar({ maxComplexity: 100, loadSource: async () => male, createModel: async () => { throw new Error('Over-budget model must not be created'); } });
await capped.ready; assert.equal(capped.model, null); assert.equal(capped.fallback.visible, true); capped.dispose();
const tiny = new RemoteAvatar({ maxComplexity: 1, loadSource: async () => male }); await tiny.ready;
assert.equal(tiny.fallback.visible, false); tiny.dispose();
const releases = [];
const resources = { jointBuffer: { destroy: () => releases.push('joints') }, meshes: [{ geometry: { dispose: () => releases.push('geometry') } }], ownedTextures: new Map([['texture', { destroy: () => releases.push('texture') }]]), materials: [{ dispose: () => releases.push('material') }] };
SkinnedModel.prototype.dispose.call(resources); SkinnedModel.prototype.dispose.call(resources);
assert.deepEqual(releases, ['joints', 'geometry', 'texture', 'material'], 'Skinned models release all per-instance GPU resources once');
console.log('Remote avatar: assets, style races, color reuse, movement, disposal and complexity limits passed');

const lodAssets = [];
let lodModels = 0;
const lod = new RemoteAvatar({loadSource: async asset => { lodAssets.push(asset); return male; }, createModel: async () => model(lodModels++ === 0 ? 2 : 4)});
await lod.ready;
const fullModel = lod.model;
fullModel.play('walk', { from: .5 });
lod.setViewDistance(20); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player-medium');
assert.equal(lod.model.current, 'walk', 'LOD replacement keeps the active animation');
assert.equal(lod.model.layers[0].time, 1, 'LOD replacement preserves normalized animation phase across clip durations');
assert.equal(fullModel.disposed, 0, 'outgoing model stays alive during its transition');
assert.deepEqual([fullModel.materials[0].uniforms.lodFade.value.x, fullModel.materials[0].uniforms.lodFade.value.y], [0, 1]);
lod.update(.1, { position: [0, 0, 0], yaw: 0, moving: true, mode: 'walk', appearance: lod.appearance });
assert.equal(fullModel.materials[0].uniforms.lodFade.value.x, .5, 'outgoing level fades over multiple frames');
assert.equal(lod.model.materials[0].uniforms.lodFade.value.x, .5, 'incoming level uses complementary fade');
lod.update(.1, { position: [0, 0, 0], yaw: 0, moving: true, mode: 'walk', appearance: lod.appearance });
assert.equal(fullModel.disposed, 1, 'outgoing model is disposed after the transition');
assert.equal(lod.model.materials[0].uniforms.lodFade.value.x, 1);
lod.setViewDistance(16); await lod.ready;
assert.equal(lodAssets.length, 2, 'Distance hysteresis avoids repeated switching');
lod.setViewDistance(50); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player-low');
lod.update(.2, { position: [0, 0, 0], yaw: 0, moving: true, mode: 'walk', appearance: lod.appearance });
lod.setViewDistance(40); await lod.ready;
assert.equal(lodAssets.length, 3);
lod.setViewDistance(10); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player');
lod.update(.2, { position: [0, 0, 0], yaw: 0, moving: true, mode: 'walk', appearance: lod.appearance });
lod.setViewDistance(12, 2); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player-medium', 'Load bias chooses lower geometry for mid-distance avatar');
lod.update(.2, { position: [0, 0, 0], yaw: 0, moving: true, mode: 'walk', appearance: lod.appearance });
lod.setViewDistance(7, 2); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player', 'Nearby avatar retains full detail even at maximum bias');
lod.update(.2, { position: [0, 0, 0], yaw: 0, moving: true, mode: 'walk', appearance: lod.appearance });
lod.setViewDistance(12, 0); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player', 'Headroom restores original distance policy');
lod.dispose();
console.log('Avatar distance LOD switching, recovery and hysteresis passed');

const avatarMaterial = avatarMaterialOptions({ name: 'boots' });
assert.ok(avatarMaterial.modules.some(module => module.name === 'lodFade'));
assert.ok(avatarMaterial.surface.includes('lodFadeVisible'));
assert.ok(avatarMaterial.shadow.includes('lodFadeVisible'));
console.log('Avatar screen-door LOD fade applies to all materials and shadows');

const interrupted = new RemoteAvatar({ loadSource: async () => male, createModel: async () => model() });
await interrupted.ready;
const interruptedOutgoing = interrupted.model;
interrupted.setViewDistance(20); await interrupted.ready;
const interruptedIncoming = interrupted.model;
interrupted.dispose();
assert.equal(interruptedOutgoing.disposed, 1, 'Disposal during an LOD fade releases the outgoing model');
assert.equal(interruptedIncoming.disposed, 1, 'Disposal during an LOD fade releases the incoming model');
console.log('Avatar disposal during an LOD fade releases both models');

const deferred = [];
const queued = {jointBuffer: {destroy: () => deferred.push('released')}, meshes: [], materials: []};
const savedEncoder = GPU.encoder;
GPU.encoder = {};
SkinnedModel.prototype.dispose.call(queued);
SkinnedModel.prototype.dispose.call(queued);
assert.deepEqual(deferred, [], 'Pending mipmap commands retain texture resources');
const submitHooks = GPU._submitHooks.splice(0);
assert.equal(submitHooks.length, 1, 'Deferred cleanup schedules only once');
for (const hook of submitHooks) hook.after?.();
assert.deepEqual(deferred, ['released']);
GPU.encoder = savedEncoder;
console.log('Pending-encoder model cleanup defers until submission');
