import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, readdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { parseGLB } from '../src/engine/loaders/GLTF.js';
import { getDetailImage } from '../src/world/terrain/DetailTextures.js';
import { appendWorldPackageAssets, disposeWorldPackage, loadWorldPackage, registerWorldPackageCollisions, unregisterWorldPackageCollisions } from '../src/network/WorldPackage.js';
import { VILLAGE_MATERIAL_ROLES } from '../src/network/WorldVillageMaterial.js';
import { validateWorldSource } from '../src/network/WorldSource.js';
import { Colliders } from '../src/world/Colliders.js';
import { standard } from '../src/materials/Materials.js';
import { decodeVegetationPlacements } from '../src/network/VegetationPlacements.js';
import { decodeReefPlacements } from '../src/network/ReefPlacements.js';
import { decodeTerrainSurfaceAsset } from '../src/network/TerrainSurfaceAsset.js';
import { BANK } from '../src/audio/soundBank.js';

const temporaryRoot = process.env.PREFIX ? path.join( process.env.PREFIX, 'tmp' ) : '/var/tmp';
const output = await mkdtemp( path.join( temporaryRoot, 'elsemesh-island-export-' ) );

try {
	const detailImage = getDetailImage();
	assert.equal( detailImage.width, 512, 'procedural placement can access the shared detail image without initializing WebGPU' );
	assert.equal( detailImage.data.length, 512 * 512 * 4, 'CPU detail image retains the exact shared RGBA data layout' );
	const checkedInDir = path.resolve( 'worlds/island' );
	const checkedInSourceBytes = await readFile( path.join( checkedInDir, 'world-source.json' ) );
	const checkedInSource = validateWorldSource( JSON.parse( checkedInSourceBytes ) );
	const referencedIDs = ( source ) => new Set( [ ...source.objects.flatMap( ( object ) => [ object.assetId, ...( object.lods || [] ).map( ( lod ) => lod.assetId ) ] ), ...source.components.flatMap( ( component ) => [ component.placementAssetId, component.dataAssetId, ...( component.beds || [] ).map( ( bed ) => bed.assetId ) ] ).filter( Boolean ) ] );
	const checkedInIDs = referencedIDs( checkedInSource );
	const checkedInFiles = ( await readdir( path.join( checkedInDir, 'assets' ) ) ).sort();
	assert.deepEqual( checkedInFiles, [ ...checkedInIDs ].map( ( id ) => id.slice( 'sha256:'.length ) ).sort(), 'checked-in island package stores exactly its referenced assets' );
	let checkedInBytes = 0;
	for ( const id of checkedInIDs ) {
		const bytes = await readFile( path.join( checkedInDir, 'assets', id.slice( 'sha256:'.length ) ) );
		checkedInBytes += bytes.length;
		assert.equal( `sha256:${createHash( 'sha256' ).update( bytes ).digest( 'hex' )}`, id, `checked-in package asset bytes must match ${id}` );
	}
	assert.ok( checkedInBytes <= checkedInSource.rules.maxPackageBytes, 'checked-in assets fit the world package budget' );
	assert.ok( checkedInSource.objects.some( ( object ) => object.id === 'tw-object:island-village' ), 'checked-in island source contains the static village GLB instance' );
	const checkedInBoat = checkedInSource.objects.find( ( object ) => object.id === 'tw-object:moored-lobster-boat' );
	assert.ok( checkedInBoat, 'checked-in island package includes its moored boat as a static visual asset' );
	assert.equal( checkedInBoat.priority, 'portal-preview', 'the moored boat is included in open portal previews' );
	assert.deepEqual( checkedInBoat.transform.position, [ 64.5, 0, 36.5 ], 'static boat instance matches the playable world dock location' );
	assert.equal( checkedInBoat.collision.enabled, false, 'static preview boat does not imply unsupported boat physics' );
	const checkedInBoatGLB = parseGLB( await readFile( path.join( checkedInDir, 'assets', checkedInBoat.assetId.slice( 'sha256:'.length ) ) ) );
	assert.ok( checkedInBoatGLB.meshes[ 0 ]?.length >= 10, 'static boat GLB includes the generated hull, cabin, deck gear, and fittings' );
	assert.ok( checkedInBoatGLB.meshes.every( ( mesh ) => mesh.every( ( primitive ) => primitive.attributes.COLOR_0 && primitive.indices?.length > 0 ) ), 'static boat GLB keeps vertex colors and indexed geometry' );
	const checkedInVegetationBytes = await readFile( path.join( checkedInDir, 'assets', checkedInSource.components[ 0 ].placementAssetId.slice( 'sha256:'.length ) ) );
	const checkedInVegetation = decodeVegetationPlacements( new Uint8Array( checkedInVegetationBytes ) );
	assert.ok( Object.values( checkedInVegetation ).filter( Array.isArray ).reduce( ( count, records ) => count + records.length, 0 ) > 100, 'checked-in component asset contains portable individual vegetation placements' );
	const sourcePath = path.join( output, 'world-source.json' );
	const firstExportOutput = execFileSync( process.execPath, [ 'tools/export-island.mjs', '--out', output ], { encoding: 'utf8' } );
	const sourceFirst = await readFile( sourcePath );
	const firstDocument = JSON.parse( sourceFirst );
	const assetPath = path.join( output, 'assets', firstDocument.objects[ 0 ].assetId.slice( 'sha256:'.length ) );
	const assetFirst = await readFile( assetPath );
	const firstAssets = new Map();
	for ( const id of new Set( [ ...firstDocument.objects.flatMap( ( object ) => [ object.assetId, ...( object.lods || [] ).map( ( lod ) => lod.assetId ) ] ), ...firstDocument.components.flatMap( ( component ) => [ component.placementAssetId, component.dataAssetId, ...( component.beds || [] ).map( ( bed ) => bed.assetId ) ] ).filter( Boolean ) ] ) ) firstAssets.set( id, await readFile( path.join( output, 'assets', id.slice( 'sha256:'.length ) ) ) );
	const secondExportOutput = execFileSync( process.execPath, [ 'tools/export-island.mjs', '--out', output ], { encoding: 'utf8' } );
	const sourceBytes = await readFile( sourcePath );
	const source = validateWorldSource( JSON.parse( sourceBytes ) );
	const assetBytes = await readFile( path.join( output, 'assets', source.objects[ 0 ].assetId.slice( 'sha256:'.length ) ) );
	assert.deepEqual( sourceBytes, sourceFirst, 'repeated source generation must be byte-identical' );
	assert.deepEqual( sourceBytes, checkedInSourceBytes, 'checked-in world source must match the clean deterministic export' );
	assert.deepEqual( assetBytes, assetFirst, 'repeated GLB generation must be byte-identical' );
	const placementID = source.components[ 0 ].placementAssetId;
	const placementBytes = await readFile( path.join( output, 'assets', placementID.slice( 'sha256:'.length ) ) );
	assert.equal( `sha256:${createHash( 'sha256' ).update( placementBytes ).digest( 'hex' )}`, placementID, 'vegetation placement asset is content addressed' );
	assert.ok( placementBytes.length < 3 * 1024 * 1024, 'compact binary placement encoding stays below three MiB' );
	assert.deepEqual( decodeVegetationPlacements( new Uint8Array( placementBytes ) ), checkedInVegetation, 'exported placements match the checked-in portable vegetation data' );
	for ( const [ id, bytes ] of firstAssets ) {
		assert.deepEqual( await readFile( path.join( output, 'assets', id.slice( 'sha256:'.length ) ) ), bytes, `repeated generation must preserve bytes for ${id}` );
		assert.equal( `sha256:${createHash( 'sha256' ).update( bytes ).digest( 'hex' )}`, id, `content-addressed asset bytes must match ${id}` );
		assert.deepEqual( await readFile( path.join( checkedInDir, 'assets', id.slice( 'sha256:'.length ) ) ), bytes, `checked-in package must contain current exported bytes for ${id}` );
	}
	const assetFiles = ( await readdir( path.join( output, 'assets' ) ) ).sort();
	assert.deepEqual( assetFiles, [ ...firstAssets.keys() ].map( ( id ) => id.slice( 'sha256:'.length ) ).sort(), 'package asset directory contains exactly the referenced unique assets' );
	assert.equal( `sha256:${createHash( 'sha256' ).update( assetBytes ).digest( 'hex' )}`, source.objects[ 0 ].assetId, 'exported asset path and source hash must match' );
	const parsed = parseGLB( assetBytes );
	const primitive = parsed.meshes[ 0 ][ 0 ];
	assert.equal( primitive.mode, 4, 'terrain export must use triangle lists' );
	assert.ok( primitive.attributes.COLOR_0, 'terrain export must carry its deterministic vertex colors' );
	assert.equal( primitive.indices.length, 512 * 512 * 6, 'terrain export must cover the full configured grid' );
	const terrainPreview = source.objects.find( ( object ) => object.id === 'tw-object:island-terrain-preview' );
	assert.ok( terrainPreview && terrainPreview.priority === 'portal-preview' && terrainPreview.collision.enabled === false, 'open portal view gets non-colliding preview terrain' );
	assert.equal( source.objects[ 0 ].replacesObjectId, terrainPreview.id, 'full terrain replaces the lightweight portal terrain' );
	const previewGLB = parseGLB( firstAssets.get( terrainPreview.assetId ) );
	assert.equal( previewGLB.meshes[ 0 ][ 0 ].indices.length, 128 * 128 * 6, 'portal terrain preview uses one sixteenth as many grid cells as full terrain' );
	assert.deepEqual( source.rules.requiredFeatures, [ 'tidewater.static-glb/1', 'tidewater.static-glb-quaternion/1', 'tidewater.village-materials/1', 'tidewater.terrain-surface/1', 'tidewater.static-vegetation/1', 'tidewater.static-reef/1', 'tidewater.island-ocean/1', 'tidewater.downeast-boat/1', 'tidewater.ambient-audio/1', 'tidewater.portal-handoff/1', 'tidewater.portal-preview-static/1' ], 'portable terrain surfaces, trusted village materials, portable vegetation and reef, ocean, boat, audio, and portals declare runtime capabilities' );
	assert.equal( source.portals[ 0 ].destinationWorldId, 'tw-world:loz-underneath', 'the example island links to the portable LOZ-derived cave' );
	assert.equal( source.components.length, 5 + source.components.filter( ( component ) => component.type === 'tidewater.static-reef/1' ).length, 'portable island declares vegetation, reef tiles, original terrain renderer, ocean, boat, and ambient components' );
	assert.equal( source.components[ 0 ].type, 'tidewater.static-vegetation/1', 'portable island uses terrain-independent, authored world-space vegetation placements' );
	assert.match( source.components[ 0 ].placementAssetId, /^sha256:[0-9a-f]{64}$/, 'vegetation placement data is content addressed' );
	assert.equal( source.components[ 0 ].priority, 'portal-preview', 'vegetation records are available for open portal previews' );
	const terrainSurface = source.components.find( ( component ) => component.type === 'tidewater.terrain-surface/1' );
	assert.equal( terrainSurface?.profile, 'example-island-v1', 'hosted island declares the compatible terrain renderer profile' );
	assert.equal( terrainSurface?.objectId, 'tw-object:island-terrain', 'terrain heightfield GLB remains the collision and fallback object' );
	assert.match( terrainSurface?.dataAssetId || '', /^sha256:[0-9a-f]{64}$/, 'terrain component links its portable surface asset' );
	assert.ok( firstAssets.has( terrainSurface.dataAssetId ), 'terrain surface asset is included in the exported package' );
	const terrainAsset = await decodeTerrainSurfaceAsset( new Uint8Array( firstAssets.get( terrainSurface.dataAssetId ) ) );
	assert.equal( terrainAsset.heights.length, terrainAsset.resolution ** 2, 'portable terrain surface contains its full-resolution heightfield' );
	assert.equal( terrainAsset.metadata.rendererProfile, 'original-tidewater-terrain-v1', 'terrain asset pins its versioned material renderer contract' );
	assert.ok( terrainAsset.metadata.material.paletteLinear.rockDark.length === 3, 'terrain package includes linear material palette parameters' );
	assert.deepEqual( source.components.find( ( component ) => component.type === 'tidewater.island-ocean/1' ), { id: 'tw-component:island-ocean', type: 'tidewater.island-ocean/1', priority: 'portal-preview' }, 'portable island declares its versioned ocean renderer for early portal previews' );
	const boat = source.components.find( ( component ) => component.type === 'tidewater.downeast-boat/1' );
	assert.deepEqual( boat, { id: 'tw-component:island-lobster-boat', type: 'tidewater.downeast-boat/1', objectId: 'tw-object:moored-lobster-boat', priority: 'portal-preview' }, 'portable island binds the trusted boat runtime to its signed world-local berth' );
	assert.equal( source.rules.seaLevel, 0, 'the boat has a declared world-space sea level' );
	assert.deepEqual( source.rules.vehiclePolicy, { enabled: true, maxSpeed: 8, maxCombinedComplexity: 100000 }, 'example island accepts transported boats with signed speed and combined-complexity limits' );
	const ambience = source.components.find( ( component ) => component.type === 'tidewater.ambient-audio/1' );
	assert.equal( ambience?.beds.length, 8, 'portable island exports its eight original ambient loop beds' );
	assert.ok( ambience.beds.every( ( bed ) => firstAssets.has( bed.assetId ) && firstAssets.get( bed.assetId ).length <= 16 * 1024 * 1024 ), 'each ambience bed is bundled as a bounded content-addressed asset' );
	const originalLoopAssets = new Map();
	for ( const entry of Object.values( BANK ) ) if ( entry.loop && entry.file ) {
		const bytes = await readFile( path.join( 'public', 'audio', entry.file ) );
		originalLoopAssets.set( `sha256:${createHash( 'sha256' ).update( bytes ).digest( 'hex' )}`, bytes );
	}
	for ( const bed of ambience.beds ) {
		const bytes = firstAssets.get( bed.assetId );
		assert.equal( `sha256:${createHash( 'sha256' ).update( bytes ).digest( 'hex' )}`, bed.assetId, 'ambient audio bytes match their signed content ID' );
		assert.deepEqual( bytes, originalLoopAssets.get( bed.assetId ), 'package transports the exact original recorded ambience bytes' );
	}
	const reefComponents = source.components.filter( ( component ) => component.type === 'tidewater.static-reef/1' );
	assert.ok( reefComponents.length > 0 && reefComponents.length <= 128, 'portable reef is divided into at most 128 nonempty tiles' );
	assert.equal( new Set( reefComponents.map( ( component ) => component.id ) ).size, reefComponents.length, 'every reef tile has a unique deterministic component ID' );
	let reefRecordCount = 0, reefAssetByteCount = 0;
	for ( const component of reefComponents ) {
		assert.equal( component.priority, 'visible', 'reef tile is requested at visible priority' );
		assert.match( component.placementAssetId, /^sha256:[0-9a-f]{64}$/, 'reef tile references a content-addressed placement asset' );
		assert.ok( Number.isFinite( component.streamingBounds.radius ) && component.streamingBounds.radius > 0, 'reef tile has bounded view-streaming metadata' );
		const bytes = firstAssets.get( component.placementAssetId );
		assert.ok( bytes?.length > 0 && bytes.length <= 16 * 1024 * 1024, 'each encoded reef tile fits the 16 MiB server asset limit' );
		const decoded = decodeReefPlacements( new Uint8Array( bytes ) );
		assert.equal( decoded.seed, 20260923, 'reef placement file records the stable procedural seed' );
		assert.ok( decoded.records.length > 0, 'reef tile assets are nonempty' );
		reefRecordCount += decoded.records.length;
		reefAssetByteCount += bytes.length;
	}
	const reefRunSummary = ( output ) => {
		const match = output.match( /Reef export: (\d+) records, (\d+) tiles, (\d+) encoded bytes/ );
		assert.ok( match, 'island exporter reports reef record, tile, and byte totals' );
		return match.slice( 1 ).map( Number );
	};
	assert.deepEqual( reefRunSummary( firstExportOutput ), [ reefRecordCount, reefComponents.length, reefAssetByteCount ], 'export summary counts match the actual reef tile assets' );
	assert.deepEqual( reefRunSummary( secondExportOutput ), reefRunSummary( firstExportOutput ), 'repeated exports report identical reef counts and bytes' );
	assert.ok( reefRecordCount > 1000, 'reef export contains its full procedural population' );
	assert.ok( source.rules.maxPackageBytes >= [ ...firstAssets.values() ].reduce( ( total, bytes ) => total + bytes.length, 0 ), 'signed package byte budget covers every unique asset' );
	assert.deepEqual( [ source.objects[ 0 ].collision.columns, source.objects[ 0 ].collision.rows ], [ 513, 513 ], 'terrain source declares the grid used for collision extraction' );
	const villageObject = source.objects.find( ( object ) => object.id === 'tw-object:island-village' );
	assert.ok( villageObject, 'export includes the procedural village and pier as portable content' );
	const villageBytes = firstAssets.get( villageObject.assetId );
	assert.ok( villageBytes?.length > 0, 'village object references its content-addressed GLB' );
	const villageGLB = parseGLB( villageBytes );
	assert.ok( villageGLB.meshes[ 0 ].length >= 8, 'village export preserves its separate authored material batches' );
	assert.ok( villageGLB.meshes[ 0 ].reduce( ( count, primitive ) => count + primitive.indices.length, 0 ) > 300000, 'village export includes the complete deterministic structural geometry' );
	assert.ok( villageGLB.meshes[ 0 ].every( ( primitive ) => primitive.attributes.COLOR_0 ), 'village export carries authored per-vertex tint' );
	assert.equal( villageObject.collision.shape, 'compound', 'village source includes the runtime builder collision layout' );
	assert.equal( villageObject.collision.boxes.length, 394, 'village collision layout matches its deterministic walkable and solid boxes' );
	assert.equal( villageObject.lods.length, 1, 'village has a separate distance LOD while retaining its full-detail base asset' );
	const villageLODBytes = firstAssets.get( villageObject.lods[ 0 ].assetId );
	assert.ok( villageLODBytes?.length > 0 && villageLODBytes.length < villageBytes.length, 'village distance LOD is a smaller content-addressed GLB' );
	const villageLOD = parseGLB( villageLODBytes );
	const triangleCount = ( model ) => model.meshes.flat().reduce( ( total, primitive ) => total + primitive.indices.length / 3, 0 );
	assert.ok( triangleCount( villageLOD ) < triangleCount( villageGLB ) * 0.5, 'village distance LOD reduces geometry by more than half' );
	assert.deepEqual( [ ...new Set( villageLOD.materials.map( material => material.extras?.tidewaterMaterial?.role ).filter( Boolean ) ) ].sort(), VILLAGE_MATERIAL_ROLES.slice().sort(), 'village distance LOD preserves the trusted material-role catalog' );
	assert.ok( villageLOD.meshes.flat().every( primitive => primitive.attributes.COLOR_0 && primitive.attributes._TW_VDATA?.itemSize === 4 ), 'village distance LOD preserves tint and trusted per-vertex material parameters' );
	assert.deepEqual( villageObject.lods[ 0 ], { assetId: villageObject.lods[ 0 ].assetId, maxScreenFraction: 0.45 }, 'village selects lower detail only when its projected size falls below the authored threshold' );
	const scannedObjects = source.objects.filter( ( object ) => object.id.startsWith( 'tw-object:scanned-debris-' ) );
	assert.equal( scannedObjects.length, 141, 'export contains debris placements generated with the playable vegetation clearances' );
	assert.ok( source.objects.every( ( object ) => object.streamingBounds && Number.isFinite( object.streamingBounds.radius ) && object.streamingBounds.radius > 0 ), 'exported island objects include local streaming bounds' );
	assert.ok( scannedObjects.every( ( object ) => Array.isArray( object.transform.rotation ) && Math.abs( Math.hypot( ...object.transform.rotation ) - 1 ) < 1e-4 && object.collision.enabled === false ), 'scanned objects carry normalized collision-free rotations' );
	const scannedAssetIDs = new Set( scannedObjects.map( ( object ) => object.assetId ) );
	assert.equal( scannedAssetIDs.size, 4, 'all four scanned debris assets are included once each' );
	for ( const id of scannedAssetIDs ) {
		const bytes = firstAssets.get( id );
		const parsed = parseGLB( bytes );
		assert.equal( parsed.meshes.length, 1, 'scanned asset export keeps a single LOD mesh' );
		assert.ok( parsed.materials[ 0 ]?.pbrMetallicRoughness?.baseColorTexture, 'scanned asset has a base-color texture' );
		assert.equal( parsed.images[ 0 ]?.mimeType, 'image/jpeg', 'scanned albedo is embedded in the GLB' );
		assert.ok( parsed.images[ 0 ]?.bytes?.length > 0, 'scanned GLB contains embedded image bytes' );
	}
	const payload = assetBytes;
	const connector = { worldId: source.worldId, manifest: { assets: [ { id: source.objects[ 0 ].assetId, priority: 'visible' } ], objects: source.objects } };
	const root = await loadWorldPackage( connector, { assets: new Map( [ [ source.objects[ 0 ].assetId, payload ] ] ) } );
	let runtimeMeshes = 0;
	root.traverse( ( object ) => {
		if ( object.isMesh ) {
			runtimeMeshes ++;
			assert.equal( object.material.vertexColors, true, 'hosted GLB renderer must enable exported vertex colors' );
		}
	} );
	assert.equal( runtimeMeshes, 1, 'runtime package loader must instantiate the exported terrain mesh' );
	const previewPayload = firstAssets.get( terrainPreview.assetId );
	const terrainManifest = { assets: [ { id: terrainPreview.assetId, priority: 'portal-preview' }, { id: source.objects[ 0 ].assetId, priority: 'visible' } ], objects: [ source.objects[ 0 ], terrainPreview ] };
	const terrainConnector = { worldId: source.worldId, manifest: terrainManifest };
	const progressiveRoot = await loadWorldPackage( terrainConnector, { assets: new Map( [ [ terrainPreview.assetId, previewPayload ] ] ), objectIDs: new Set( [ terrainPreview.id ] ) } );
	assert.equal( progressiveRoot.children[ 0 ].visible, true, 'preview terrain is visible while high detail is not loaded' );
	await appendWorldPackageAssets( terrainConnector, progressiveRoot, new Map( [ [ source.objects[ 0 ].assetId, payload ] ] ), { objectIDs: new Set( [ source.objects[ 0 ].id ] ) } );
	assert.equal( progressiveRoot.children.find( ( object ) => object.userData.worldObjectId === terrainPreview.id ).visible, false, 'full terrain hides the preview when it arrives' );
	assert.equal( progressiveRoot.children.find( ( object ) => object.userData.worldObjectId === source.objects[ 0 ].id ).visible, true, 'full terrain remains visible after replacement' );
	const villagePayload = villageBytes.buffer.slice( villageBytes.byteOffset, villageBytes.byteOffset + villageBytes.byteLength );
	const villageMaterials = Object.fromEntries( VILLAGE_MATERIAL_ROLES.map( role => [ role, standard( { name: role } ) ] ) );
	const villageConnector = { worldId: source.worldId, manifest: { rules: source.rules, assets: [ { id: villageObject.assetId, priority: 'visible' }, { id: villageObject.lods[ 0 ].assetId, priority: 'visible' } ], objects: [ villageObject ] }, getAsset: async id => firstAssets.get( id ) };
	const villageRoot = await loadWorldPackage( villageConnector, { assets: new Map( [ [ villageObject.assetId, villagePayload ] ] ), materialContext: { materials: villageMaterials, textures: { bake() {} } } } );
	let villageRuntimeMeshes = 0;
	const villageRoles = new Set();
	villageRoot.traverse( ( object ) => { if ( object.isMesh ) { villageRuntimeMeshes ++; assert.equal( object.geometry.getAttribute( 'vdata' )?.itemSize, 4, 'village GLB keeps original material parameters' ); assert.equal( object.geometry.getAttribute( 'color' )?.itemSize, 3, 'village GLB keeps authored tint' ); villageRoles.add( object.material.name ); } } );
	assert.equal( villageRuntimeMeshes, villageGLB.meshes[ 0 ].length, 'hosted package loader creates each village material batch' );
	assert.deepEqual( villageRoles, new Set( VILLAGE_MATERIAL_ROLES ), 'hosted village selects every original trusted material role' );
	const villageLODController = villageRoot.userData.worldPackage.lodControllers.get( villageObject.id );
	await villageLODController.loadLevel( 1, new AbortController().signal );
	let villageLODMeshes = 0;
	villageRoot.traverse( object => { if ( object.isMesh && object.geometry.getAttribute( 'vdata' ) ) villageLODMeshes ++; } );
	assert.equal( villageLODMeshes, villageRuntimeMeshes + villageLOD.meshes[ 0 ].length, 'hosted village loader builds the low LOD with the same trusted material context' );
	const villageColliders = new Colliders();
	registerWorldPackageCollisions( villageRoot, villageColliders );
	assert.equal( villageColliders.boxes.length, villageObject.collision.boxes.length, 'hosted village registers every authored collider' );
	assert.ok( villageColliders.boxes.some( ( box ) => box.walkable ) && villageColliders.boxes.some( ( box ) => ! box.walkable && box.solid ), 'hosted village retains both walkable surfaces and solid obstacles' );
	unregisterWorldPackageCollisions( villageRoot, villageColliders );
	assert.equal( villageColliders.boxes.length, 0, 'hosted village removes all colliders on world handoff' );
	const deferredObject = { ...source.objects[ 0 ], id: 'tw-object:deferred-copy', label: 'Deferred copy', transform: { position: [ 20, 0, 20 ], yaw: 0 }, collision: { shape: 'none', enabled: false } };
	const filteredConnector = { worldId: source.worldId, manifest: { assets: [ { id: source.objects[ 0 ].assetId, priority: 'visible' } ], objects: [ source.objects[ 0 ], deferredObject ] } };
	const filteredRoot = await loadWorldPackage( filteredConnector, { assets: new Map( [ [ source.objects[ 0 ].assetId, payload ] ] ), objectIDs: new Set( [ source.objects[ 0 ].id ] ) } );
	assert.deepEqual( filteredRoot.userData.worldPackage.loadedObjects, new Set( [ source.objects[ 0 ].id ] ), 'view streaming appends only selected instances even when assets are shared' );
	const testRotation = [ 0, 0, Math.SQRT1_2, Math.SQRT1_2 ];
	const rotatedObject = { ...source.objects[ 0 ], transform: { position: [ 1, 2, 3 ], yaw: Math.PI / 2, rotation: testRotation }, collision: { shape: 'none', enabled: false } };
	const rotatedConnector = { worldId: source.worldId, manifest: { assets: [ { id: rotatedObject.assetId, priority: 'visible' } ], objects: [ rotatedObject ] } };
	const rotatedRoot = await loadWorldPackage( rotatedConnector, { assets: new Map( [ [ rotatedObject.assetId, payload ] ] ) } );
	assert.ok( Math.abs( rotatedRoot.children[ 0 ].quaternion.z - Math.SQRT1_2 ) < 1e-6 && Math.abs( rotatedRoot.children[ 0 ].quaternion.w - Math.SQRT1_2 ) < 1e-6, 'runtime package loader applies signed quaternion transforms' );
	const colliders = new Colliders();
	registerWorldPackageCollisions( root, colliders );
	assert.equal( colliders.heightfields.length, 1, 'hosted terrain package registers its heightfield collision' );
	let terrainPosition;
	root.children[ 0 ].traverse( ( object ) => { if ( object.isMesh ) terrainPosition = object.geometry.getAttribute( 'position' ); } );
	assert.ok( terrainPosition, 'terrain package exposes its GLB vertex positions to collision extraction' );
	const sample = 128 * 513 + 256;
	const px = terrainPosition.getX( sample ), py = terrainPosition.getY( sample ), pz = terrainPosition.getZ( sample );
	assert.ok( Math.abs( colliders.groundHeightAt( px, pz, Infinity ) - py ) < 1e-4, 'heightfield collision matches exported GLB terrain vertex height' );
	unregisterWorldPackageCollisions( root, colliders );
	assert.equal( colliders.heightfields.length, 0, 'world handoff removes the hosted terrain heightfield' );
	const packageState = root.userData.worldPackage;
	disposeWorldPackage( root );
	assert.equal( packageState.disposed, true, 'canceled or discarded world packages release their parsed render resources' );
	assert.equal( packageState.parsed.size, 0, 'package disposal clears parsed GLB roots' );
	disposeWorldPackage( root );
	disposeWorldPackage( villageRoot );
	disposeWorldPackage( filteredRoot );
	disposeWorldPackage( rotatedRoot );
	disposeWorldPackage( progressiveRoot );
	console.log( 'ok deterministic procedural island terrain and village GLB package' );
} finally {
	await rm( output, { recursive: true, force: true } );
}
